logging:
  level:
    org:
      springframework:
        web : DEBUG
        security : DEBUG
    org.hibernate.SQL: DEBUG

spring:
  application:
    name : authorization
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:3000/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://localhost:8080/logout"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
