logging:
  level:
    org:
      springframework:
        web : DEBUG
        security : DEBUG
    org.hibernate.SQL: DEBUG

spring:
  application:
    name : authorization
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2
    username: root
    password: 15411541
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  encryptor:
    password: password
    salt: 626F6F746966756C
server:
  port: 9000
