logging:
  level:
    org:
      springframework:
        web : DEBUG
        security : DEBUG
    org.hibernate.SQL: DEBUG

spring:
  application:
    name : authorization
  datasource:
    url: jdbc:mysql://localhost:3306/oauth3
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: kimssafy1030@gmail.com
    password: vzxkizmiaqcjrknm
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


jwt:
  encryptor:
    password: password
    salt: 626F6F746966756C
server:
  port: 9000
  address: 0.0.0.0
