logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
spring:
  application:
    name : authorization
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: password
