logging:
  level:
    org.springframework.security: DEBUG
spring:
  application:
    name: authorization
  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:db;MODE=MYSQL
  #    username: sa
  #    password
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ssafy
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
  data:
    redis:
      host: localhost
      port: 6379
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: kimssafy1030@gmail.com
    password: vzxkizmiaqcjrknm
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false