spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 52d077cf5e47ef46b0bedeb883a86a15
            client-secret: ureG7DX796KIHubTi8KZKfwbtwy9HmN0
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            provider: kakao
            scope:
              - profile_nickname
              - account_email

          naver:
            client-id: 1iuOXUXX5oO2ML3ClacW
            client-secret: mI5FN78DD5
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-name: naver
            authorization-grant-type: authorization_code
            scope: name,email

          google:
            client-id: 711962988723-p9ck1o47i2hbroskipfn7l4666g9t8tl.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-name: google
            authorization-grant-type: authorization_code
            scope: profile,email

          oidc-client:
            client-id: oidc-client
            client-secret: secret
            client-name: oidc-client
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/login/oauth2/code/oidc-client
            scope: openid, profile
            client-authentication-method: client_secret_post

        provider:
          oidc-client:
            authorization-uri: http://localhost:8080/oauth2/authorize
            token-uri: http://localhost:8080/oauth2/token
            user-info-uri: http://localhost:8080/userinfo
            user-name-attribute: id

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response