spring:

  application:
    name: client
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false
  config:
    import:
      - application-oauth.yml
      - application-jwt.yml


server:
  port: 8080
  forward-headers-strategy: framework
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        RestTemplate: DEBUG

